# config.yaml
organism: "Klebsiella pneumoniae"
email: "your@email.com"
retmax: 10

paths:
  metadata_dir: "data/metadata"
  sequences_dir: "data/sequences"
  ast_dir: "data/ast"
  results_dir: "results"
  reference_db_dir: "ref_db"