#paths
paths:
  metadata_dir: "data/metadata"
  host_metadata_dir: "data/host_metadata"
  sequences_dir: "data/sequences"
  ast_dir: "data/ast"
  results_dir: "results"
  reference_db_dir: "ref_db"

# Configuration for carabapenem breakingpoints 
carabapenems:
  - imipenem
  - meropenem
  - doripenem
  - ertapenem
  - biapenem

#Carabapenem breaking points EUCAST 2025
breakpoints:
  doripenem: [1, 2]
  ertapenem: [0.5, 0.5]
  imipenem: [2, 4]
  imipenem-relebactam: [2, 2]
  meropenem: [2, 2]
  meropenem-vaborbactam: [8, 8]

#configuration for preprocessing columns
preprocessing:
  structural:
    split_location: true
    split_mic: true
    split_latlon: true

  location:
    source_column: "geographic location"
    target_columns: ["Country", "State/Province"] #location column is split into these two
    latlon_column: "latitude and longitude"

  mic_split:
    column_contains:
      - "measurement"
    exclude_contains:
      - "sign"
      - "unit"
  encoding:
    encode_units: true
    units:
      units_column_contains:
        - "units"        # substring to detect unit-columns
      mapping:
        "mg/l": 1
        "mm": 2
    
    encode_comparison_signs: true
    sign_column_contains:
      - "measurement sign"
      - "_sign"
    comparison_signs:
      "<":  -2
      "<=": -1
      "==": 0
      "=":  0
      ">=": 1
      ">":  2

    encode_phenotypes: true
    phenotype:
      phenotype_column_contains:
        - "phenotype"
        - "resistance phenotype"
        - "_phen"
      #https://www.eucast.org/bacteria/clinical-breakpoints-and-interpretation/definition-of-s-i-and-r/
      eucast_phenotype_mapping: 
        - "S": 0
        - "I": 1
        - "R": 2
      mapping:
        "n": -1
        "nd": -1
        "not defined": -1
        "s": 0
        "sensitive": 0
        "susceptible": 0
        "i": 1
        "intermediate": 1
        "ns": 1
        "nonsusceptible": 1
        "ssd": 1
        "susceptible-dose dependent": 1
        "r": 2
        "resistant": 2
        "hlar": 2
        "high level aminoglycoside resistance": 2

  drop:
    explicit: #drop columns with explicit names
      - "BioSample"
      - "Run"
      - "isolate"
      - "collected by"
      - "collection date"
      - "host subject id"
      - "sample"
      - "organism_complex"

    contains: #drop columns that contains below texts
      - "vendor"
      - "laboratory typing"
      - "testing standard"
      - "_id"